version: '3.7'
services:
  # Base de Dados Relacional
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: clinica_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # Servidor HAPI FHIR
  hapi-fhir:
    image: hapiproject/hapi:latest
    ports:
      - "9090:8080"
    volumes:
      - .:/fhir8080

  # ----------------------------------------------------
  #  EHRBASE
  # ----------------------------------------------------

  # Base de Dados para o EHRbase
  ehrbase-db:
    image: postgres:16
    environment:
      POSTGRES_DB: ehrbase
      POSTGRES_USER: ehrbase
      POSTGRES_PASSWORD: ehrbase
    ports:
      - "5433:5432"
    volumes:
      - ./init-ehr.sql:/docker-entrypoint-initdb.d/init-ehr.sql

  # Servidor EHRbase
  ehrbase:
    image: ehrbase/ehrbase:2.31.0
    depends_on:
      - ehrbase-db
    ports:
      - "8085:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ehrbase-db:5432/ehrbase
      SPRING_DATASOURCE_USERNAME: ehrbase
      SPRING_DATASOURCE_PASSWORD: ehrbase
      SPRING_FLYWAY_USER: ehrbase
      SPRING_FLYWAY_PASSWORD: ehrbase
      SECURITY_AUTHTYPE: none

  # API de Integração
  api:
    build: .
    container_name: integration-service
    ports:
      - "5000:5000"
    depends_on:
      - hapi-fhir
      - ehrbase
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=clinica_db
      - DB_USER=user
      - DB_PASS=password
      - EHRBASE_URL=http://ehrbase:8080/ehrbase/rest/openehr/v1
      - FHIR_SERVER_URL=http://hapi-fhir:8080/fhir

  # Frontend Streamlit
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: pce-dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_app:/app/streamlit_app
    depends_on:
      - api
      - hapi-fhir
      - ehrbase
    environment:
      - FASTAPI_URL=http://integration-service:5000
      - EHRBASE_URL_LOCAL=http://ehrbase:8080/ehrbase/rest/openehr/v1
      - HAPI_FHIR_URL=http://hapi-fhir:8080/fhir
