[theme]
base = "light"
primaryColor = "#f2afc6"
backgroundColor = "#cbe0f6"
secondaryBackgroundColor = "#e5f0fc"
textColor = "#1e293b"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
